# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 254)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(12, 7, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 60, 451, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(11, 40, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.submit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.submit_btn.setGeometry(QtCore.QRect(370, 180, 80, 23))
        self.submit_btn.setObjectName("submit_btn")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 90, 421, 83))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.access_key_id_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.access_key_id_lineEdit.setObjectName("access_key_id_lineEdit")
        self.gridLayout.addWidget(self.access_key_id_lineEdit, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.secret_access_key_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.secret_access_key_lineEdit.setObjectName("secret_access_key_lineEdit")
        self.gridLayout.addWidget(self.secret_access_key_lineEdit, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.region_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.region_lineEdit.setObjectName("region_lineEdit")
        self.gridLayout.addWidget(self.region_lineEdit, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(323, 47, 41, 16))
        self.label_6.setObjectName("label_6")
        self.access_user = QtWidgets.QLabel(self.centralwidget)
        self.access_user.setGeometry(QtCore.QRect(364, 48, 59, 15))
        self.access_user.setObjectName("access_user")
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(280, 180, 80, 23))
        self.clear_btn.setObjectName("clear_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AWS IAM : Python Qt"))
        self.label.setText(_translate("MainWindow", "Amazon Web Services"))
        self.label_2.setText(_translate("MainWindow", "IAM Services"))
        self.submit_btn.setText(_translate("MainWindow", "Submit"))
        self.label_3.setText(_translate("MainWindow", "Access Key Id"))
        self.label_4.setText(_translate("MainWindow", "Secret Access Key"))
        self.label_5.setText(_translate("MainWindow", "Region"))
        self.label_6.setText(_translate("MainWindow", "User : "))
        self.access_user.setText(_translate("MainWindow", "TextLabel"))
        self.clear_btn.setText(_translate("MainWindow", "Clear"))

